INCLUDE(${CMAKE_ROOT}/Modules/CheckIncludeFileCXX.cmake)


function(checkHeaderAssert HFILE)
	check_include_file_cxx(${ARGV0} HAVE_${ARGV0})
	if(NOT HAVE_${ARGV0})
		message(FATAL_ERROR "not have ${ARGV0}")
	else()
		message(STATUS "have ${ARGV0}")
	endif()
endfunction(checkHeaderAssert)

function(checkHeaderWarn HFILE)
	check_include_file_cxx(${ARGV0} HAVE_${ARGV0})
	if(NOT HAVE_${ARGV0})
		message(WARNING "not have ${ARGV0}")
	else()
		message(WARNING "have ${ARGV0}")
	endif()
endfunction(checkHeaderWarn)

checkHeaderAssert("stdint.h")
checkHeaderAssert("stddef.h")
checkHeaderAssert("stdint.h")
checkHeaderAssert("stdio.h")
checkHeaderAssert("string.h")
checkHeaderAssert("stdlib.h")
checkHeaderAssert("sys/types.h")
checkHeaderAssert("fcntl.h")
checkHeaderAssert("unistd.h")
checkHeaderAssert("dirent.h")
checkHeaderAssert("time.h")
checkHeaderAssert("math.h")
checkHeaderAssert("vector")
checkHeaderAssert("string")
checkHeaderAssert("list")
checkHeaderAssert("limits")
checkHeaderAssert("map")
checkHeaderAssert("set")
checkHeaderAssert("memory")
checkHeaderAssert("functional")